name: Node.js Package

on:
  workflow_dispatch:
  push:
    branches: [ test/workflow ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Configures the node version used on GitHub-hosted runners
      - run: ls /usr/bin
        
